### ISSUE TITLE
Any chance to make it compatible with latest DNN 9.6.2

### ISSUE THREAD

**Issue by Scippy** [sachatrauwaen/OpenUrlRewriter#22]
Hi, I love this module, it come on with very useful providers!
It is one of the fundamental modules that I use for my work!
The problem is that with latest DNN 9.6.2 and with 2SXC 11.04.00 it give me some problem.
[https://github.com/dnnsoftware/Dnn.Platform/issues/3816](url)
[https://github.com/2sic/2sxc/issues/2144](url)
Is there any possibility of making a new release with the necessary corrections to make this module compatible again with these latest versions?

**Comment by sachatrauwaen** [comment]
I published a prerealse for dnn 9.6

It will be nice if you can test it and give some feedback

**Comment by Scippy** [comment]
Hi Sacha,
I've tested but it still has some problems, for example the two problems mentioned above are still present.
If it helps you can take a look at my Fork that I am currently using without any errors.
[https://github.com/Scippy/OpenUrlRewriter](https://github.com/Scippy/OpenUrlRewriter)

**Comment by hu3mu** [comment]
Hi Scippy,
i am new to github and looking for a dnn-urlrewriter. I looked your fork and downloaded the code as a zip-file. But i can't install that as an extension in dnn. What am i doing wrong? Can you give me a link to a install-version please? Thanks for your help.

**Comment by Scippy** [comment]
> Hi Scippy,
> i am new to github and looking for a dnn-urlrewriter. I looked your fork and downloaded the code as a zip-file. But i can't install that as an extension in dnn. What am i doing wrong? Can you give me a link to a install-version please? Thanks for your help.

Hi, I’ll prepare an installation packages in the next days.

**Comment by hu3mu** [comment]
Great news! Thanks.

 

Von: Scippy <notifications@github.com> 
Gesendet: Freitag, 4. September 2020 08:17
An: sachatrauwaen/OpenUrlRewriter <OpenUrlRewriter@noreply.github.com>
Cc: GerritGer <gerrit.stoever@online.de>; Comment <comment@noreply.github.com>
Betreff: Re: [sachatrauwaen/OpenUrlRewriter] Any chance to make it compatible with latest DNN 9.6.2 (#22)

 

Hi Scippy,
i am new to github and looking for a dnn-urlrewriter. I looked your fork and downloaded the code as a zip-file. But i can't install that as an extension in dnn. What am i doing wrong? Can you give me a link to a install-version please? Thanks for your help.

Hi, I’ll prepare an installation packages in the next days.

**Comment by Scippy** [comment]
@GerritGer have a look here [https://github.com/Scippy/OpenUrlRewriter/releases/tag/V1.4.5](https://github.com/Scippy/OpenUrlRewriter/releases/tag/V1.4.5)

**Comment by hu3mu** [comment]
Thanks a lot, i got it installed without problem. Now i have to figure out how it works with the ventrian news articles und property agent.

 

Von: Scippy <notifications@github.com> 
Gesendet: Mittwoch, 9. September 2020 17:18
An: sachatrauwaen/OpenUrlRewriter <OpenUrlRewriter@noreply.github.com>
Cc: GerritGer <gerrit.stoever@online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [sachatrauwaen/OpenUrlRewriter] Any chance to make it compatible with latest DNN 9.6.2 (#22)

 

@GerritGer <https://github.com/GerritGer>  have a look here https://github.com/Scippy/OpenUrlRewriter/releases/tag/V1.4.5

**Comment by Scippy** [comment]
@GerritGer you can find latest Ventrian PA release with OpenUrlRewriter provider here [https://github.com/Scippy/Property-Agent/releases/tag/Property-Agent](https://github.com/Scippy/Property-Agent/releases/tag/Property-Agent)

**Comment by hu3mu** [comment]
Hi Scippy, 

 

thanks for the info with the link.

 

After installing your

OpenUrlRewriter                                          1.4.5

Satrabel OpenUrlRewriter module

 

and the latest Ventrian PA release, i can open the settings page fort he url rewriter.

 

But after installing the PA OpenUrlRewriter provider Version 1.3.2  i get the following error when i try to open the settings page.

 

 

http://dnn9.hallo-bergstrasse.de/admin/open-url-rewriter?error=Method+not+found%3a+%27System.Collections.Generic.List%601%3cVentrian.PropertyAgent.PropertyInfo%3e+Ventrian.PropertyAgent.PropertyController.List(Int32%2c+Int32%2c+Ventrian.PropertyAgent.SearchStatusType%2c+Int32%2c+Int32%2c+Boolean%2c+Ventrian.PropertyAgent.SortByType%2c+Int32%2c+Ventrian.PropertyAgent.SortDirectionType%2c+System.String%2c+System.String%2c+Int32%2c+Int32%2c+Boolean)%27. <http://dnn9.hallo-bergstrasse.de/admin/open-url-rewriter?error=Method+not+found%3a+%27System.Collections.Generic.List%601%3cVentrian.PropertyAgent.PropertyInfo%3e+Ventrian.PropertyAgent.PropertyController.List(Int32%2c+Int32%2c+Ventrian.PropertyAgent.SearchStatusType%2c+Int32%2c+Int32%2c+Boolean%2c+Ventrian.PropertyAgent.SortByType%2c+Int32%2c+Ventrian.PropertyAgent.SortDirectionType%2c+System.String%2c+System.String%2c+Int32%2c+Int32%2c+Boolean)%27.&content=0> &content=0

 

Do you have an idea what went wrong?

 

I am working with dnn 9.6.2

 

Gerrit

 

 

Von: Scippy <notifications@github.com> 
Gesendet: Donnerstag, 10. September 2020 09:28
An: sachatrauwaen/OpenUrlRewriter <OpenUrlRewriter@noreply.github.com>
Cc: GerritGer <gerrit.stoever@online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [sachatrauwaen/OpenUrlRewriter] Any chance to make it compatible with latest DNN 9.6.2 (#22)

 

@GerritGer <https://github.com/GerritGer>  you can find latest Ventrian PA release with OpenUrlRewriter provider here https://github.com/Scippy/Property-Agent/releases/tag/Property-Agent

**Comment by Scippy** [comment]
Which PA version have you installed?
If you've installed my latest PA 1.10.11 release you need also to update the PA Url Rewriter Provider, in that case try to replace this dll [Satrabel.OpenUrlRewriter.PropertyAgent.dll.zip](https://github.com/sachatrauwaen/OpenUrlRewriter/files/5288228/Satrabel.OpenUrlRewriter.PropertyAgent.dll.zip) in the bin folder (unzip before replace)

**Comment by hu3mu** [comment]
Hi Scippy,

 

yes i have installed your latest PA release and PA URL Rewriter Provider. After replacing the dll the error disappeared. Thanks.

 

Now i still get a long  URl  

 

http://dnn9.hallo-bergstrasse.de/locations-finden/ausflugsziele/odenwald/sehenswertes/burg-schloss-kloster/burg-frankenstein

 

/locations-finden/  = pagename of the PA- module

/ausflugsziele/odenwald/sehenswertes/burg/schloss-kloster/  = Type of  the Property

/burg-frankenstein  = Customfield oft he Property

 

I would like a short URL like

 

http://dnn9.hallo-bergstrasse.de/burg-frankenstein

 

What should i do to get a url like this?

 

Gerrit

 

 

Scippy <notifications@github.com> 
Gesendet: Sonntag, 27. September 2020 14:05
An: sachatrauwaen/OpenUrlRewriter <OpenUrlRewriter@noreply.github.com>
Cc: GerritGer <gerrit.stoever@online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [sachatrauwaen/OpenUrlRewriter] Any chance to make it compatible with latest DNN 9.6.2 (#22)

 

Which PA version have you installed?
If you've installed my latest PA release you need to update the PA Url Rewriter Provider, in that case try to replace this dll
Satrabel.OpenUrlRewriter.PropertyAgent.dll.zip <https://github.com/sachatrauwaen/OpenUrlRewriter/files/5288228/Satrabel.OpenUrlRewriter.PropertyAgent.dll.zip>  in the bin folder (unzip before replace)

**Comment by Scippy** [comment]
Look the url after cleared the DNN server cache.

**Comment by hu3mu** [comment]
HI,

after clearing alle the  caches i still get the long url:

 

http://dnn9.hallo-bergstrasse.de/locations-finden/museum/senckenbergmuseum-frankfurt

 

This URL also works (i get it from the protper search result list)

 

http://dnn9.hallo-bergstrasse.de/bergstrasse/senckenbergmuseum-frankfurt/PropertyID/49

 

Are there some settings which i should change?  

 

Gerrit

 

 

 

 

Von: Scippy <notifications@github.com> 
Gesendet: Mittwoch, 30. September 2020 14:57
An: sachatrauwaen/OpenUrlRewriter <OpenUrlRewriter@noreply.github.com>
Cc: GerritGer <gerrit.stoever@online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [sachatrauwaen/OpenUrlRewriter] Any chance to make it compatible with latest DNN 9.6.2 (#22)

 

Look the url after cleared the DNN server cache.

**Comment by Scippy** [comment]
To enable OpenUrlRewrite on PA you must disable "Do Redirect" in PA SEO settings, then clear cache.
![Screenshot_4](https://user-images.githubusercontent.com/16607338/94730221-2e65c800-0363-11eb-8ebb-195801eacaa0.jpg)

**Comment by hu3mu** [comment]
Hi,

 

„Do Redirect“ is unchecked.

 

If I leave „View property Title“ empty I get an url like this: 

 

http://dnn9.hallo-bergstrasse.de/locations-finden/museum/87-odenwald

 

87 is the propertyID 

„Odenwald“ ist the value from my first customfield „Region“

 

 

 

Von: Scippy <notifications@github.com> 
Gesendet: Mittwoch, 30. September 2020 21:24
An: sachatrauwaen/OpenUrlRewriter <OpenUrlRewriter@noreply.github.com>
Cc: GerritGer <gerrit.stoever@online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [sachatrauwaen/OpenUrlRewriter] Any chance to make it compatible with latest DNN 9.6.2 (#22)

 

To enable OpenUrlRewrite on PA you must disable "Do Redirect" in PA SEO settings, then clear cache.
 <https://user-images.githubusercontent.com/16607338/94730221-2e65c800-0363-11eb-8ebb-195801eacaa0.jpg>

**Comment by Scippy** [comment]
It is right. The Property ID is used for duplicated title. You can personalize page title working around view property layout file

![Screenshot_1](https://user-images.githubusercontent.com/16607338/94794708-8b519480-03dc-11eb-8133-73beaa59c592.jpg)

**Comment by hu3mu** [comment]
Hi,

changing the settings for the Page title doesn’t change the URl. I would like an URL without the Typefields. I tried several times with different SEO-Settings for  „View Type title“   e.g. blank field, [Type:0]  or [Type:-1] Everytime i get the full type-fields in the url.  I have no idea what else i could try.

 

Gerrit

 

Von: Scippy <notifications@github.com> 
Gesendet: Donnerstag, 1. Oktober 2020 11:53
An: sachatrauwaen/OpenUrlRewriter <OpenUrlRewriter@noreply.github.com>
Cc: GerritGer <gerrit.stoever@online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [sachatrauwaen/OpenUrlRewriter] Any chance to make it compatible with latest DNN 9.6.2 (#22)

 

It is right. The Property ID is used for duplicated title. You can personalize page title working around view property layout file

 <https://user-images.githubusercontent.com/16607338/94794708-8b519480-03dc-11eb-8133-73beaa59c592.jpg>

**Comment by Scippy** [comment]
Yes it is right. There are two different setting to do: page URL and page Title
The page URL always contains full type path, you can personalize only last field through SEO Layout Settings
Page Title instead, it is completely customizable in View Property Layout File

**Comment by hu3mu** [comment]
Thanks for the info, too bad, that there is no way to get rid of the type Path. 

 

What about the ventrian news Arcticles? Do i need an url Provider to get a short URL like www.mysite.com/ArticleTitle?  On a older screenshort  for the Site setting  of „Open Url Rewriter“  i saw an entry „NewsArticlesUrlRuleProvider“. Do i need this provider ? I could find it.

 

Von: Scippy <notifications@github.com> 
Gesendet: Freitag, 2. Oktober 2020 08:40
An: sachatrauwaen/OpenUrlRewriter <OpenUrlRewriter@noreply.github.com>
Cc: GerritGer <gerrit.stoever@online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [sachatrauwaen/OpenUrlRewriter] Any chance to make it compatible with latest DNN 9.6.2 (#22)

 

Yes it is right. There are two different setting to do: page URL and page Title
The page URL always contains full type path, you can personalize only last field through SEO Layout Settings
Page Title instead, it is completely customizable in View Property Layout File
